### ISSUE TITLE
Does ReCAM  promote the accuracy of multi-label classification? 

### ISSUE THREAD

**Issue by myt889** [zhaozhengChen/ReCAM#1]
Hi, thanks your excellent work. I am following the multi-label classification task. And I would like to know  that if your poposed ReCAM can promote the accuracy of multi-label classification?

Looking forward to your reply. Thanks!

Best Regards!
Tan

**Comment by zhaozhengChen** [comment]
Hi @myt889,

No, although ReCAM can generate better CAM (higher mIou), the accuracy of multi-label classification is not better, even slightly worse.

**Comment by myt889** [comment]
Ok, I get it. Thanks again.

**Comment by zhaozhengChen** [comment]
welcome!
