### ISSUE TITLE
about the segmentation network

### ISSUE THREAD

**Issue by woqiaow** [zhaozhengChen/ReCAM#14]
Hello, thank you for your code. I try to replace the SegmentationClass with the generated pseudo-masks, but I found that the SegmentationClass has 2913 pictures, but the generated pseudo-masks only has 1464 pictures. Is there anything else to do?

How to deal with it so as to complete the segmentation network training with the generated pseudo-masks?

**Comment by zhaozhengChen** [comment]
Hi, thanks for your interest in our work.

'SegmentationClass' contains _train_ and _val_ images (1464+1449).
To train the segmentation, we use the _train_aug_ (10582) images. You need to generate pseudo masks for all 10582 images first.

**Comment by woqiaow** [comment]
Thank you for your answer, do you mean to generate (10582) pseudo masks to replace the SegmentationClass folder?

And train_aug(10582) images are used for training segmentation, and val(1449) images are used for verification, Do you mean this?

**Comment by zhaozhengChen** [comment]
yes

**Comment by woqiaow** [comment]
thank you!

**Comment by woqiaow** [comment]
> Hi, thanks for your interest in our work.
> 
> 'SegmentationClass' contains _train_ and _val_ images (1464+1449). To train the segmentation, we use the _train_aug_ (10582) images. You need to generate pseudo masks for all 10582 images first.

Hello, is val(1449) images used to verify after training the segmentation  network with train_aug(10582) images? Or other images are needed to verify the segmentation network？Could you tell me？
Do val(1449) images need to regenerate pseudo masks?
