### ISSUE TITLE
cam_eval_thres and sem_seg_bg_thres

### ISSUE THREAD

**Issue by YangjiaqiDig** [zhaozhengChen/ReCAM#15]
As I am running on my own dataset, the make_sem_seg_label process is the slowest one in the project, do you suggest I should make sem_seg_bg_thres close to cam_eval_thres value?
I can make the cam iou calculated through 0.1 - 1 (cam_eval_thres) to select the best threshold, but not a good idea to do the make sem seg running through the range... so do you think I should try the sem_seg_bg_thres rounding cam_eval_thres as a start?

Besides, what about conf_fg_thres and conf_bg_thres? should I just leave them original value coz they r for separate inter-pixel trianning? Or should I modify them based on cam_eval_thres as well?

Thank you!

**Comment by YangjiaqiDig** [comment]
Probably I  can save the probability map instead of the cls label png, and check the best sem_seg_bg_thres after the inference?

**Comment by zhaozhengChen** [comment]
1. the conf_fg_thres and conf_bg_thres should be modified based on the cam_eval_thres. You can try to set conf_fg_thres = cam_eval_thres + 0.1 (or 0.15), conf_bg_thres = cam_eval_thres - 0.1 
2. Yes, you can the probability map and then select the best threshold.

**Comment by YangjiaqiDig** [comment]
> 1. the conf_fg_thres and conf_bg_thres should be modified based on the cam_eval_thres. You can try to set conf_fg_thres = cam_eval_thres + 0.1 (or 0.15), conf_bg_thres = cam_eval_thres - 0.1
> 2. Yes, you can the probability map and then select the best threshold.

Thanks!!
