### ISSUE TITLE
mIoU after irnet

### ISSUE THREAD

**Issue by YangjiaqiDig** [zhaozhengChen/ReCAM#17]
is that possible the mIoU after irnet train and random walk would be lower than mIoU in first ReCAM?
I worked on my own dataset, but get lower ACC after the irn step (make_sem_seg_labels)

**Comment by zhaozhengChen** [comment]
I think it shouldn't be if you set reasonable thresholds to train irnet and inference.

**Comment by YangjiaqiDig** [comment]
> I think it shouldn't be if you set reasonable thresholds to train irnet and inference.

okay, thanks. Just too slow to tune the params for irn step
