### ISSUE TITLE
Hello,can you help me

### ISSUE THREAD

**Issue by liubaohu111** [zhaozhengChen/ReCAM#18]
can you provide your training weights give me? Thank you!

**Comment by zhaozhengChen** [comment]
Hi, could you please clarify which training weights you are referring to?

**Comment by liubaohu111** [comment]
> 嗨，您能否澄清一下您指的是哪些训练重量？

The weight of making recam, the graph of recam trained by myself on my side is all black graphs, and miou is only 0.17

> 嗨，您能否澄清一下您指的是哪些训练重量？

**Comment by liubaohu111** [comment]
> 嗨，您能否澄清一下您指的是哪些训练重量？

Can you give me the files in the YOUR_WORK_SPACE you generated for a generative experiment

> > 嗨，您能否澄清一下您指的是哪些训练重量？
> 
> The weight of making recam, the graph of recam trained by myself on my side is all black graphs, and miou is only 0.17
> 
> > 嗨，您能否澄清一下您指的是哪些训练重量？

Can you give me the files in the YOUR_WORK_SPACE you generated for a generative experiment

**Comment by zhaozhengChen** [comment]
On Voc dataset?

**Comment by liubaohu111** [comment]
> 




> 在 Voc 数据集上？

The VOC dataset hasn't changed! How is the mask generated by the cam_to_ir_label.py file black, isn't it a heat map?

**Comment by zhaozhengChen** [comment]
Yes, it should be heat maps.

**Comment by liubaohu111** [comment]
> cam_to_ir_label.py

ir_label this folder contains heat maps?

**Comment by zhaozhengChen** [comment]
It contains the input of the next step (train_irn). You may refer to the paper of IRN for more details.

**Comment by zbb1111** [comment]
Hello, I also encountered this problem, I generated it is also black, I see that the palette in the code is only defined, not used?
