### ISSUE TITLE
make_cam.py

### ISSUE THREAD

**Issue by liubaohu111** [zhaozhengChen/ReCAM#19]
make_cam.py this file doesn't need to be run separately?

**Comment by zhaozhengChen** [comment]
Yes. You can run by the following command:
`CUDA_VISIBLE_DEVICES=0 python run_sample.py --voc12_root ./VOCdevkit/VOC2012/ --work_space YOUR_WORK_SPACE --train_cam_pass True --train_recam_pass True --make_recam_pass True --eval_cam_pass True`

**Comment by liubaohu111** [comment]
> 
thank for you help
