### ISSUE TITLE
as a leanrner i want to tell u guys, the ''pydensecrf''pakage just fit to py36 and no higher version..

### ISSUE THREAD

**Issue by Dlemand** [zhaozhengChen/ReCAM#2]
my heart break .QAQ

**Comment by zhaozhengChen** [comment]
Hi, 
did you encounter some problems when you try to install 'pydensecrf' in a higher python version?
I tried to install it in python 3.8 and it worked...

**Comment by Dlemand** [comment]
well, that sounds good，My py==3.8.10. it can not goes well .
which command you used to install? 
Thanks.

**Comment by zhaozhengChen** [comment]
you may try this command:
`pip install cython`
`pip install git+https://github.com/lucasb-eyer/pydensecrf.git`

**Comment by Dlemand** [comment]
thank you very much! i fixed it.  
i download the git project and use the command 
`python setup.py install`

**Comment by zhaozhengChen** [comment]
welcome!
