### ISSUE TITLE
ask

### ISSUE THREAD

**Issue by 7real7** [zhaozhengChen/ReCAM#20]
Hello, is there any library in the dependency file yml that is not needed? The yml file you provided is too rich. Support Support

**Comment by zhaozhengChen** [comment]
Yes, many libraries are not needed, I just export the conda env I used.
 I suggest installing pytorch, numpy, pydensecrf, and opencv-python first, and then check if any additional libraries are required.

**Comment by 7real7** [comment]
Thank you very much! Your paper has greatly inspired me! Learn from you.

**Comment by zhaozhengChen** [comment]
Thanks for your interest in our work.
