### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by 7real7** [zhaozhengChen/ReCAM#22]
Sorry to bother you again. In Step 2 of your README, my understanding is that after training the multi label classification task, CAM is generated. Then, CAM is used to train the multi category classification task and re extract ReCAM. Why did you omit the step of generating CAM in the training steps you provided? Could you please answer it when you have time? Thank you

**Comment by zhaozhengChen** [comment]
There is no need to generate CAMs and save them as separate files, as they are generated dynamically during the ReCAM training process. You can refer to Line 90 in the train_recam.py file for more information.

Additionally, it's important to note that the weights of ResNet-50 change throughout the ReCAM training process. As a result, we must generate CAMs dynamically.

**Comment by 7real7** [comment]
The meaning is to repeatedly generate CAM and provide it to ReCAM for training, right?

**Comment by zhaozhengChen** [comment]
Exactly! 
One more thing is that we don't need extra (or very little) computational overhead because the computation of CAM is very simple.

**Comment by 7real7** [comment]
you bet! The cost is indeed very low, which is very suitable for people like us who lack sufficient computing power. I understand that during the training process of ReCAM, the extraction of CAM will also become more accurate, so that after the classification model converges, the extraction of ReCAM will also be very good

**Comment by zhaozhengChen** [comment]
Yes, it can also improve the quality of CAM.

**Comment by 7real7** [comment]
Thank you very much for taking up your valuable time
