### ISSUE TITLE
The question about ‘UperNet-Swin’

### ISSUE THREAD

**Issue by diaodiao317** [zhaozhengChen/ReCAM#25]
Hello, I would like to ask which code you used to get the results of the UperNet-Swin part of your paper. Is there a related project on github, or did you rewire the uppernet code yourself. Looking forward to your reply, thank you.

**Comment by zhaozhengChen** [comment]
Hi, thanks for your interest in our work, and sorry for the late reply.
We use [mmsegmentaion](https://github.com/open-mmlab/mmsegmentation) to get the UperNet-Swin result.

**Comment by diaodiao317** [comment]
Thanks for your reply!

**Comment by diaodiao317** [comment]
I'm sorry to bother you again. I've recently attempted to reproduce your paper using UperNet-Swin and conducted some of my own experiments. However, I couldn't find the corresponding configuration in mmseg. It seems that only ade20k configurations are available. I made some simple modifications to them, but the results were not satisfactory. Could you please inform me which network backbone you used, whether it was tiny, base, or large? If you could provide the relevant configuration files, that would be even more helpful. I'm looking forward to your response.

**Comment by zhaozhengChen** [comment]
Hi, 

I'm sorry I cannot find the config files I used. Swin paper only provides config files on the ade20k dataset, and we made some modifications based on them. You may refer to the config file from the official Swin GitHub page at this [link](https://github.com/SwinTransformer/Swin-Transformer-Semantic-Segmentation/tree/main/configs/swin). 

Regarding the backbone, we use Swin-base. 

Hope this will be helpful to you.

**Comment by diaodiao317** [comment]
OK I have tried tiny, base and large in the past few days. Tiny and base are both lower than the data in your paper, while large is significantly higher than the data in the paper. I will continue to try the base backbone. I guess that the lower effect than the paper may be due to the pre-training weights and windowsize. I will continue to try. Anyway, thank you very much for your reply. Best wishes！
