### ISSUE TITLE
ValueError: only one element tensors can be converted to Python scalars

### ISSUE THREAD

**Issue by YYDS-cc** [zhaozhengChen/ReCAM#4]
Thank you for your work，bro.
But encountered some problems during training,when I perform step2 of VOC, there is an error in the loss calculation，just like：

avg_meter.add({'loss_ce': loss_ce.item()})
ValueError: only one element tensors can be converted to Python scalars

I don't know how to solve this error, please help me.
Thank you！

**Comment by zhaozhengChen** [comment]
Thanks for your interest in our work!

I think the reason is that loss_ce is more than one element. You may print loss_ce to see what is it.
But it shouldn't happen if you didn't modify the code and use the same environment.

**Comment by YYDS-cc** [comment]
I seem to know the reason for the error.
The environment is the same, but I have selected multiple GPUs，when use the 'torch.nn.DataParallel',it will return the same amount of loss as gpus.
Thanks a lot!
