### ISSUE TITLE
Pseudo labels on COCO train set

### ISSUE THREAD

**Issue by rulixiang** [zhaozhengChen/ReCAM#6]
Hey, can you provide the pseudo labels for semantic segmentation on the COCO train set?

**Comment by zhaozhengChen** [comment]
Sure, which one do you want? The one with mIoU 46.3?

**Comment by rulixiang** [comment]
Yes! Thank you very much!😁

**Comment by zhaozhengChen** [comment]
Please find it at this [link](https://drive.google.com/file/d/1Mvj_qztGi6_1FHw5FJavuDzVOw6uRfLz/view?usp=sharing).

**Comment by rulixiang** [comment]
Thanks again!
