### ISSUE TITLE
Training stages

### ISSUE THREAD

**Issue by lsa1997** [zhaozhengChen/ReCAM#7]
Hi, thanks for this excellent work. 
I notice ReCAM adopts a two-stage training strategy that trains FC layer-1 first. What if training FC 1&2 together directly? Will it be harmful to the performance?

**Comment by zhaozhengChen** [comment]
Thanks for your interest in our work.
Yes, it would be harmful. The class-specific feature will be noisy if we train FC1&FC2 together from scratch, and then FC2 may overﬁt to the noisy features.

**Comment by lsa1997** [comment]
Thanks for your reply!
